### ISSUE TITLE
Translation and deployment 

### ISSUE THREAD

**Issue by DeepSpace2** [aatishb/maskmath#2]
Hi. I just came across minutephysics' video and the maskmath website. Great job!

I thought it would be great if we could come up with some mechanism that will allow people to fork this repo, translate the text to whatever language, then create a pull request. After each pull request is merged a CI/CD process will deploy the website with the new translation (of course, language-selection buttons will be available on the page itself).

Already forked and started to work on my translation :)

**Comment by DeepSpace2** [comment]
I just saw that this is hosted by github pages, so this should be extremely easy :)

Please see my current attempt on https://deepspace2.github.io/maskmath/. It's very basic. The `select` element `change` event shows and hides relevant `p` elements . Each translation/language text is in its own `p` element, with the `class` attribute being the same as the 2-letters language code (which is also the `value` of the `option` element).

**Comment by aatishb** [comment]
Hi there, 

Thanks for creating this issue & for your interest in adding translations. I'd love to add translations and a few people have also already indicated interest in translating this to other languages.

One simple way to go about this would be to make a copy of the index.html page for each language (I think all the text content is contained in that one page). So e.g. we could add an index-es.html for spanish, and so on, and provide a link on the index.html page to all of the translations. This might make it easier for people without coding experience to add translations. Although there are probably some cons to this approach?

Another way might be to use something like [vue i18n](https://github.com/kazupon/vue-i18n). I'm not so familiar with that, but am open to thoughts on how best to go about adding translations. My instinct is to go for a quick solution that would be simplest for contributors to add translations.

**Comment by nlehuen** [comment]
I can contribute a French translation when the process is clear!

**Comment by DeepSpace2** [comment]
@aatishb Glad you liked the initiative.

To be honest I think vue i18n might be an overkill (and it doesn't provide for people with no coding experience).
I went ahead with my approach and I think it will be cumbersome to maintain and to "explain" to people how to contribute translations. 

I did like your first suggestion, having a dedicated `index-<langauge>.html` for each language, but I'm afraid that will have the same issues as the previous approaches.

I think what we can do is "templatize" the current `index.html`, and load the translations from a `<language-code>.json` file, but I'm not sure what the keys in such file would be (it would be weird to have the entire English sentence as key, it will also be problematic with the styling).

**Comment by DeepSpace2** [comment]
@aatishb I agree, I think having a separate page for each language might be the simplest.

**Comment by aatishb** [comment]
Added a contributor's guide for translations here: https://github.com/aatishb/maskmath/issues/4

**Comment by aatishb** [comment]
@DeepSpace2 feel free to close this if it's resolved. @nlehuen you're welcome to take on a French translation.
