### ISSUE TITLE
Issue with Page Width on Hebrew Translation

### ISSUE THREAD

**Issue by aatishb** [aatishb/maskmath#24]
On the [Hebrew translation](https://aatishb.com/maskmath/index-he.html), it's possible to scroll left to a large blank space on the left side of the page. If I remove the `dir="rtl"` from the body tag (which indicates that text is read right to left), this seems to fix the issue. I don't understand the cause for the bug, but maybe making this change and adding `dir="rtl"` to the children div of `<body>` instead will fix it?

cc @DeepSpace2

**Comment by DeepSpace2** [comment]
Interesting.,. This only happens on Firefox. On Chrome and Edge there are no horizontal scrollbar and also when clicking the middle-mouse button it's not possible to scroll horizontally.

![image](https://user-images.githubusercontent.com/6841988/93189740-2d218200-f74b-11ea-80f8-d59e3d1c1b2e.png)

Anyway I solved it by adding a `div` with `dir="rtl" under `body`.
