### ISSUE TITLE
Visualization for the Umbrella example

### ISSUE THREAD

**Issue by pankgeorg** [aatishb/maskmath#38]
> Masks don't guarantee safety, they reduce risk. This is a lot like how an umbrella doesn't guarantee that you'll stay dry, but it does reduce your chance of getting wet. Like umbrellas, masks only work if you use them correctly. But unlike umbrellas, which only protect people who use them, masks also protect people around the wearer.

My mom, teacher at a mid school (children 12-15 years old) taught both the essay and the video to her students.

The umbrella example flied _really_ well in all the classes (it may as well be the only thing that really rang a bell), so I'm suggesting to create a fancy visual for that too.

How does the idea sound? I may be able to assist with the coding (even though I don't have any experience yet).

**Comment by aatishb** [comment]
Hi @pankgeorg, that's nice to hear the umbrella example resonated with school children. I'm inclined to not make major edits to the interactive essay –– I'd prefer to minimize the changes now that it's published, and it may also be a bit complicated to propagate these additions to the translations. However I think an umbrella visual or even a more kid-friendly version of this article would be a fun idea for a remix on a separate branch/url, and I'm all for trying to make this material more accessible to a wider audience. We could list these remixes on the Github page here to help people find them.
