### ISSUE TITLE
The translation list font is too thin

### ISSUE THREAD

**Issue by kisaragi-hiu** [aatishb/maskmath#60]
The translations list is barely readable because it's a thin font used for small text.

A font weight of eg. 400 would also help scripts not covered by Raleway to not stand out as much.

Raleway 200:

![raleway 200 on 16px](https://user-images.githubusercontent.com/11722318/105860910-77880900-6031-11eb-9ab8-490ff64af3a3.png)

Raleway 400:

![raleway 400](https://user-images.githubusercontent.com/11722318/105860919-7951cc80-6031-11eb-9e2b-6d3e3b064754.png)

**Comment by aatishb** [comment]
Thanks for this @kisaragi-hiu, I bumped up the font weight as you suggested and also the font size a tad. (apologies for the delay)

**Comment by aatishb** [comment]
@kisaragi-hiu I'm happy to add you to the contributor list for filing this, let me know if that's ok with you.

**Comment by kisaragi-hiu** [comment]
Sure!

**Comment by aatishb** [comment]
@all-contributors add @kisaragi-hiu for design
